apiVersion: apps/v1
kind: Deployment
metadata:
  name: iroussev
  labels:
    app: iroussev
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: iroussev
  template:
    metadata:
      labels:
        app: iroussev
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: frontend
              containerPort: 3000
              protocol: TCP
            - name: backend
              containerPort: 3001
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: FRONTEND_PORT
              value: "3000"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}