apiVersion: v1
kind: Service
metadata:
  name: iroussev
spec:
  type: {{ .Values.service.type }}
  selector:
    app: iroussev
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
