apiVersion: v1
kind: Service
metadata:
  name: iroussev
  labels:
    app: iroussev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: frontend
      protocol: TCP
      name: frontend
    - port: 3001
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    app: iroussev