apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitor
type: Opaque
stringData:
  additional-scrape-configs.yaml: |-
    - job_name: 'blackbox_targets'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://jenkins.iroussev.com
          - https://argocd.iroussev.com
          - https://iroussev.com
          - https://grafana.iroussev.com
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter.monitor.svc.cluster.local:9115