replicaCount: 1

image:
  repository: iroussevcom/site
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location /.well-known/acme-challenge/ {
        allow all;
      }
  path: /
  pathType: Prefix
  hosts:
    - iroussev.com
  tls:
    - secretName: iroussev-tls
      hosts:
        - iroussev.com